baseurl: "https://lucasscvvieira.github.io/"
languageCode: "pt-br"
title: "Blog do Lucas"
theme: "hugo-tania"
paginate: 6

disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  # titleEmoji: 💻

  # Logo will show before the blog title on site navbar.
  # titleLogo: favicon.ico

  # Enable float footnotes.
  # Default to true
  enableFootnotes: true

  siteName: "Hugo Tania is Amazing"
  siteDesc: "Hugo is Absurdly Fast!"
  author: "Lucas Campos Vieira"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github: "https://github.com/lukerops/"
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:

  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: lukerops/lukerops.github.io
      id: R_kgDOHraWIw
      category:
        name: Comments
        id: DIC_kwDOHraWI84CRFdE

menu:
  header:
    - name: Posts
      url: "/posts/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
